export const countryCodes = [
    { code: "+51", country: "Perú", flag: "🇵🇪", maxDigits: 9 },
    { code: "+1", country: "Estados Unidos/Canadá", flag: "🇺🇸", maxDigits: 10 },
    { code: "+52", country: "México", flag: "🇲🇽", maxDigits: 10 },
    { code: "+34", country: "España", flag: "🇪🇸", maxDigits: 9 },
    { code: "+54", country: "Argentina", flag: "🇦🇷", maxDigits: 10 },
    { code: "+57", country: "Colombia", flag: "🇨🇴", maxDigits: 10 },
    { code: "+55", country: "Brasil", flag: "🇧🇷", maxDigits: 11 },
    { code: "+56", country: "Chile", flag: "🇨🇱", maxDigits: 9 },
    { code: "+49", country: "Alemania", flag: "🇩🇪", maxDigits: 11 },
    { code: "+213", country: "Argelia", flag: "🇩🇿", maxDigits: 9 },
    { code: "+966", country: "Arabia Saudita", flag: "🇸🇦", maxDigits: 9 },
    { code: "+61", country: "Australia", flag: "🇦🇺", maxDigits: 9 },
    { code: "+43", country: "Austria", flag: "🇦🇹", maxDigits: 10 },
    { code: "+32", country: "Bélgica", flag: "🇧🇪", maxDigits: 9 },
    { code: "+591", country: "Bolivia", flag: "🇧🇴", maxDigits: 8 },
    { code: "+86", country: "China", flag: "🇨🇳", maxDigits: 11 },
    { code: "+82", country: "Corea del Sur", flag: "🇰🇷", maxDigits: 10 },
    { code: "+506", country: "Costa Rica", flag: "🇨🇷", maxDigits: 8 },
    { code: "+53", country: "Cuba", flag: "🇨🇺", maxDigits: 8 },
    { code: "+45", country: "Dinamarca", flag: "🇩🇰", maxDigits: 8 },
    { code: "+593", country: "Ecuador", flag: "🇪🇨", maxDigits: 9 },
    { code: "+20", country: "Egipto", flag: "🇪🇬", maxDigits: 10 },
    { code: "+503", country: "El Salvador", flag: "🇸🇻", maxDigits: 8 },
    { code: "+971", country: "Emiratos Árabes", flag: "🇦🇪", maxDigits: 9 },
    { code: "+63", country: "Filipinas", flag: "🇵🇭", maxDigits: 10 },
    { code: "+358", country: "Finlandia", flag: "🇫🇮", maxDigits: 10 },
    { code: "+33", country: "Francia", flag: "🇫🇷", maxDigits: 9 },
    { code: "+502", country: "Guatemala", flag: "🇬🇹", maxDigits: 8 },
    { code: "+594", country: "Guayana Francesa", flag: "🇬🇫", maxDigits: 9 },
    { code: "+592", country: "Guyana", flag: "🇬🇾", maxDigits: 7 },
    { code: "+509", country: "Haití", flag: "🇭🇹", maxDigits: 8 },
    { code: "+504", country: "Honduras", flag: "🇭🇳", maxDigits: 8 },
    { code: "+91", country: "India", flag: "🇮🇳", maxDigits: 10 },
    { code: "+62", country: "Indonesia", flag: "🇮🇩", maxDigits: 11 },
    { code: "+972", country: "Israel", flag: "🇮🇱", maxDigits: 9 },
    { code: "+39", country: "Italia", flag: "🇮🇹", maxDigits: 10 },
    { code: "+81", country: "Japón", flag: "🇯🇵", maxDigits: 10 },
    { code: "+254", country: "Kenia", flag: "🇰🇪", maxDigits: 10 },
    { code: "+60", country: "Malasia", flag: "🇲🇾", maxDigits: 10 },
    { code: "+212", country: "Marruecos", flag: "🇲🇦", maxDigits: 9 },
    { code: "+505", country: "Nicaragua", flag: "🇳🇮", maxDigits: 8 },
    { code: "+234", country: "Nigeria", flag: "🇳🇬", maxDigits: 10 },
    { code: "+47", country: "Noruega", flag: "🇳🇴", maxDigits: 8 },
    { code: "+64", country: "Nueva Zelanda", flag: "🇳🇿", maxDigits: 9 },
    { code: "+31", country: "Países Bajos", flag: "🇳🇱", maxDigits: 9 },
    { code: "+507", country: "Panamá", flag: "🇵🇦", maxDigits: 8 },
    { code: "+595", country: "Paraguay", flag: "🇵🇾", maxDigits: 9 },
    { code: "+351", country: "Portugal", flag: "🇵🇹", maxDigits: 9 },
    { code: "+1-787", country: "Puerto Rico", flag: "🇵🇷", maxDigits: 10 },
    { code: "+44", country: "Reino Unido", flag: "🇬🇧", maxDigits: 10 },
    { code: "+1-809", country: "República Dominicana", flag: "🇩🇴", maxDigits: 10 },
    { code: "+7", country: "Rusia", flag: "🇷🇺", maxDigits: 10 },
    { code: "+65", country: "Singapur", flag: "🇸🇬", maxDigits: 8 },
    { code: "+27", country: "Sudáfrica", flag: "🇿🇦", maxDigits: 9 },
    { code: "+46", country: "Suecia", flag: "🇸🇪", maxDigits: 9 },
    { code: "+41", country: "Suiza", flag: "🇨🇭", maxDigits: 9 },
    { code: "+66", country: "Tailandia", flag: "🇹🇭", maxDigits: 9 },
    { code: "+216", country: "Túnez", flag: "🇹🇳", maxDigits: 8 },
    { code: "+90", country: "Turquía", flag: "🇹🇷", maxDigits: 10 },
    { code: "+598", country: "Uruguay", flag: "🇺🇾", maxDigits: 8 },
    { code: "+58", country: "Venezuela", flag: "🇻🇪", maxDigits: 10 },
    { code: "+84", country: "Vietnam", flag: "🇻🇳", maxDigits: 10 },
]
